import dynamic from 'next/dynamic'
import { Suspense } from 'react'
import Layout from "@/components/layout/Layout"
import Loading from './loading'

// Dynamically import heavy components
const Category = dynamic(() => import("@/components/sections/Category"))
const DealProduct1 = dynamic(() => import("@/components/sections/DealProduct1"))
const Product1 = dynamic(() => import("@/components/sections/Product1"))
const Shop = dynamic(() => import("@/components/sections/Shop"))
const Slider1 = dynamic(() => import("@/components/sections/Slider1"))
export const metadata = {
  title: 'Ninico - Minimal NextJS React Template',
  description: 'Generated by create next app',
}
export default function Home() {
    return (
        <Layout headerStyle={1} footerStyle={1}>
            <Suspense fallback={<Loading />}>
                <Slider1 />
                <Suspense fallback={<Loading />}>
                    <Category />
                </Suspense>
                <Suspense fallback={<Loading />}>
                    <Product1 />
                </Suspense>
                <Suspense fallback={<Loading />}>
                    <DealProduct1 />
                </Suspense>
                <Suspense fallback={<Loading />}>
                    <Shop />
                </Suspense>
            </Suspense>
        </Layout>
    )
}